#!/bin/bash
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
reject() {
  if printf '%s\n' "$1" | bash "$root/scripts/check-header-paths.sh"; then
    echo "Expected absolute path rejection: $1" >&2
    exit 1
  fi
}
reject '/* Generated from /Volumes/Build/hwp.h */'
reject '#include "/opt/toolchain/header.h"'
reject '/* source: /arbitrary/location.rs */'
reject '/* source: C:\build\source.rs */'
printf '%s\n' '/* Generated by cbindgen. Do not edit. */' '/** API documentation */' '//normal comment' '#include <stdint.h>' \
  'void hwp_engine_string_free(char *value);' | bash "$root/scripts/check-header-paths.sh"
echo 'Header absolute-path checks passed'
